### ISSUE TITLE
iOS 14?

### ISSUE THREAD

**Issue by radiochild577** [rrroyal/Harbour#1]
Been using Harbour on my iPhone 11 Pro before it was even released as a TestFlight beta (sideloaded from github source). Love this project and happy to see that it's moving towards an app store release. One question though - I'm still on iOS 14 for work reasons, and cannot upgrade to iOS 15 yet. Is there any reason why the TestFlight build requires iOS 15 as the minimum compatible version? Any chance for iOS 14 being supported?

**Comment by radiochild577** [comment]
That would be awesome. I'll be updating to iOS 15 eventually but the timeline is out of my hands. Even a limited iOS 14 compatible build, workout future support, would be GREATLY appreciated!

**Comment by rrroyal** [comment]
That tells me all I need. I'll look into that, thanks!

**Comment by rrroyal** [comment]
Can you check these ones (if one works, ignore the rest):
[- Harbour-tbd-optional.ipa.zip](https://github.com/rrroyal/Harbour/files/7352845/Harbour-tbd-optional.ipa.zip)
[- Harbour-tbd-required.ipa.zip](https://github.com/rrroyal/Harbour/files/7352848/Harbour-tbd-required.ipa.zip)
[- Harbour-dylib-optional.ipa.zip](https://github.com/rrroyal/Harbour/files/7352852/Harbour-dylib-optional.ipa.zip)
[- Harbour-dylib-required.ipa.zip](https://github.com/rrroyal/Harbour/files/7352854/Harbour-dylib-required.ipa.zip)

**Comment by rrroyal** [comment]
What about [this one](https://github.com/rrroyal/Harbour/files/7357325/Harbour.ipa.zip)?

**Comment by rrroyal** [comment]
Click the "tag" icon in the top right corner and tap "Refresh" - if you have only one endpoint it should select it automatically, but if it won't, select one from the list.

iOS 14 doesn't support multiple sheets, so the Setup/Login screen isn't presented on the first run - it works fine on the *full* build ☺️

**Comment by rrroyal** [comment]
It may be that, but not necessarily. You can drag down on the error notification and it will show the whole message.

Can you catch the failing request through proxy and send me the response? It may be possible that I'm decoding something wrong 😖

**Comment by radiochild577** [comment]
How would I catch the fading request through proxy? Sorry, not sure exactly what you mean here. I run a reverse proxy on my LAN, but couldn't connect through that in Harbour. Had to enter the IP:port of my docker machine to connect in the app. Happy to help do this if you can explain a little more 🙂

Also the app does not save my login info between app launches

**Comment by rrroyal** [comment]
Can you try [this one](https://github.com/rrroyal/Harbour/files/7360587/Harbour.ipa.zip), use it for a bit, then go to `Settings → 🤫 → Copy logs`, remove private/sensitive stuff and send them to my [e-mail](mailto:royal@shameful.xyz)?
I've never saw any errors regarding missing data, so I'm really confused 😶‍🌫️
