### ISSUE TITLE
ANSI Console Colors in Container Logs

### ISSUE THREAD

**Issue by ExtremTechniker** [rrroyal/Harbour#10]
The Container logs are printed raw into the UI.

If logs contains ANSI Console Colors they are printed, instead the should be colored in the color of the color code.

![Ohne Titel](https://user-images.githubusercontent.com/34032662/160878551-3d0de658-260b-4a11-a819-28a01d548866.png)

normally it should by like this 
![Bildschirmfoto 2022-03-30 um 17 59 55](https://user-images.githubusercontent.com/34032662/160879420-48cdfe15-7591-4de0-ab52-bf57c3811599.png)

**Comment by rrroyal** [comment]
[v4.0.0 #24](https://github.com/rrroyal/Harbour/releases/tag/%2324) :)
