### ISSUE TITLE
Selecting an option for a container only works briefly

### ISSUE THREAD

**Issue by kylefmohr** [rrroyal/Harbour#12]
First off thanks for making this open source! The design is fantastic, it feels more useful, in a lot of ways, than Portainer because it's less intimidating and has a very crisp UI.

**Describe the bug**
Whenever I select a container, then select one of the four options near the top (Mounts, Config, Network, or Logs), it successfully loads that screen, but after 1-5 seconds it kicks me out of that screen, back to the container view. ~~[Here's a screen recording of the behavior](https://user-images.githubusercontent.com/6644803/180587148-4e66de32-b224-4f8a-95d4-62b97d34c127.mp4)~~ [That link seems broken, try this instead](https://gfycat.com/pleasedcloudykakarikis)

Additionally, and this is much more minor, but in the settings menu, when I click on the first option, which is the dropdown with my server name, it shows two identical instances of the server, and shows that they're both "in use". [Screenshot](https://user-images.githubusercontent.com/6644803/180587279-8a677636-be33-4067-a6b9-9bf3a29bc64c.png)

**To Reproduce**
1. Select any active container from the main menu
2. Select either "Mounts", "Network", "Config", or "Logs"
3. Wait

**Expected behavior**
Allow browsing of these menus

**Details (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 15.4.1
 - Harbour version v2.0.0#7 (Tried both TestFlight and Sideloaded)
 - Portainer version 2.14.1

**Comment by rrroyal** [comment]
hi! do you have a auto-refresh on by any chance? it could be caused by it.

it will be definitely fixed in the next release (which will be in about a month - including iOS 16 goodies)

**Comment by kylefmohr** [comment]
Yep, sure enough, turning off auto-refresh fixed the issue. Thank you!
