### ISSUE TITLE
The data couldn't be read because it is missing

### ISSUE THREAD

**Issue by KovD3v** [rrroyal/Harbour#13]
**Describe the bug**
App show an error but there aren't any error
error: Error! The data couldn't be read because it is missing

**Details**
 - Device: 13,2 (12)
 - OS: 15.6
 - Harbour version v2.0.0#7
 - Portainer version [e.g. 2.9.2]

**Container create command **:
docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always -v  portainer_data:/data portainer/portainer-ce

**Screenshots**
![IMG_364313A309FF-1](https://user-images.githubusercontent.com/106698548/183117940-5aad2cab-adb6-4ff8-9089-c5ef9514d3b2.jpeg)
![IMG_81559436CAC1-1](https://user-images.githubusercontent.com/106698548/183117956-50bc31b8-3d28-4b6b-b34c-65344b6c57d8.jpeg)

**Comment by luc-ass** [comment]
Same here.

**Details**

- Device: iPhone X
- OS: 15.6 (19G71)
- Harbour version v2.0.0 (#7)
- Portainer version: v2.14.3

**Container create command**
docker run -d -p 9443:9443 -p 9090:9000 --name=portainer --restart=always -v <local_folder>:/data portainer/portainer-ce:2.14.3

**Comment by rrroyal** [comment]
i'll try to push a fix sometime soon

**Comment by luc-ass** [comment]
No pressure at all! Just wanted to give an update about affected versions.

This project is amazing!!

**Comment by KovD3v** [comment]
I fully agree, this project is fantastic, keep it up

**Comment by PIORIGIN** [comment]
I agree too, thanks you !

**Comment by dan3o3** [comment]
Any news to this? Wonder why this only happens to my Synology docker, Alpine/Ubuntu based dockers are running fine...

**Comment by KovD3v** [comment]
> Any news to this? Wonder why this only happens to my Synology docker, Alpine/Ubuntu based dockers are running fine...

Same on synology DS220+

**Comment by pchristod** [comment]
Synology seems to be the culprit. I'm seeing the same error and I discovered this App just yesterday. I'm using a DS918+

**Comment by Kerber0ss** [comment]
At 3615xs same problem.

**Comment by prolixlive** [comment]
This is happening on Portainer BE 2.15 running in Arch Linux as well. 

![35B88DBB-69E9-4DC7-B1A1-0AE414FC0327](https://user-images.githubusercontent.com/106646357/189249505-bef09c26-7116-4ca4-aed2-524d49deeee1.png)
![52FF389A-147F-46DF-A5D4-CF5AD652C4B1](https://user-images.githubusercontent.com/106646357/189249506-fe9a52f6-8dd0-4eb7-9e90-ccabfcbfe1f0.png)
 
 iPhone 13 Pro Max, iOS 15.6.1

**Comment by PhillipDiCarlo** [comment]
Unraid docker running image: "portainer/portainer-ce" also results in the same error.

**Comment by rrroyal** [comment]
this should work in 3.0.0 - could you all check if the issue still persists?

**Comment by luc-ass** [comment]
It's wow working! thank you so much 😊
