### ISSUE TITLE
Multiple Portainer

### ISSUE THREAD

**Issue by stanthewizzard** [rrroyal/Harbour#14]
Hello

Coudl you ease multiple portainer selection (something near settings maybe ?)

Awesome APP

**Comment by rrroyal** [comment]
there already is - tap on endpoint in settings and you should be able to add more from there

**Comment by stanthewizzard** [comment]
I did add the portainer but not that easy to switch when using
thanks

**Comment by rrroyal** [comment]
this should be easier in 3.0.0 - could you check?

**Comment by stanthewizzard** [comment]
Easier than ever :)
THANKS
