### ISSUE TITLE
Self-Signed Certificates support

### ISSUE THREAD

**Issue by cpwood** [rrroyal/Harbour#18]
I run Portainer with a self-signed SSL certificate. Would be handy to have an option (defaulted to "off") for ignoring certificate validation errors. I can't currently use Harbour because of this.

**Comment by rrroyal** [comment]
this should work in 3.0.0 - could you check?

**Comment by cpwood** [comment]
Appreciate you looking at this! Unfortunately I’m receiving the
following error:

**Comment by cpwood** [comment]
Looks like the screenshot didn't arrive from my email, sorry!

However! Good news! I've got it working. I hadn't trusted my custom root CA in iOS. As soon as I did this, it worked!

Thanks

**Comment by ZuluPro** [comment]
@cpwood  How did you do ?

@rrroyal Does this work without the trick above ?
I have the following error:

```
(4) 2023-04-20T17:36:41Z [PortainerStore] Failed to get endpoints: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, NSErrorPeerCertificateChainKey=(
    "<cert(0x12907b600) s: Cloud Mercato i: Cloud Mercato>"
), NSErrorClientCertificateStateKey=0, NSErrorFailingURLKey=https://portainer.cloud-mercato.lan/api/endpoints, NSErrorFailingURLStringKey=https://portainer.cloud-mercato.lan/api/endpoints, NSUnderlyingError=0x12ca8f700 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x12ce15470>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x12907b600) s: Cloud Mercato i: Cloud Mercato>"
)}}, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <EAF32310-90E8-46D [<decode: missing data>]
```

**Comment by rrroyal** [comment]
Yup, the error says `An SSL error has occurred and a secure connection to the server cannot be made`, so it's some sort of an issue with the SSL certificate.

You can trust the certificate by [following these steps](https://support.apple.com/en-us/HT204477).
