### ISSUE TITLE
Error while opening a container to check it and the config tab is empty

### ISSUE THREAD

**Issue by eeeple** [rrroyal/Harbour#2]
Since portainer 2.9.2, a red error indicating that Harbour cannot read data has appeared.
![image](https://user-images.githubusercontent.com/2037523/141675889-7c2006e8-21f6-42fb-87ea-36aca6142d59.png)

**Comment by rrroyal** [comment]
I'll investigate!

**Comment by eeeple** [comment]
Sorry for the very low quality bug report.
Here's some more info!

**Software used:**
- Harbour version : 2.0.0 #4
- Portainer version : 2.9.2

**What happens:**
> When opening a container in Harbour, a truncated red message pops up indicating that some info could not be read

**What should happen:**
> No error should appear

**Other impacts**
> The "config" tab appears empty (maybe that's the part Harbour cannot read?)[1]
Everything else seems to be working as intended.

[1]
![image](https://user-images.githubusercontent.com/2037523/141677071-41c5b4b0-d3e4-4285-b3a8-880551978c29.png)

**Comment by rrroyal** [comment]
Just got back to it - could you dump the container (or at least supply me with the docker-compose/creation command)?

**Comment by rrroyal** [comment]
please let me know if it works now (168a1e44618cd8bf1344b4413e2f36eea738c566 / v2.0.0#5) :)

**Comment by rrroyal** [comment]
closed - please reopen if its still happening
