### ISSUE TITLE
TestFlight expired

### ISSUE THREAD

**Issue by Prolonz** [rrroyal/Harbour#20]
The TestFlight has expired. Rejoining the test doesn’t work either. It would be great to get access to the app again. 

Thanks for all the work on this great app!

**Comment by Bradyns** [comment]
I'm experiencing this as well.

**Comment by manic-code** [comment]
3rd person with this problem, would appreciate a renewal of the TestFlight beta for all.

**Comment by fmnamado** [comment]
Me also
Can’t rejoin in the link
Can’t open the app
Doesn’t appear in test flight
Sadness installed 😰

**Comment by rrroyal** [comment]
i've released a new build :)

**Comment by fmnamado** [comment]
Yes i confirm it opens now, thank you 🙏 

After updating, i lost all my configs
Add to re input my server details

**Comment by fmnamado** [comment]
Hello,
I can’t use it again. It has expires
It says i must update my device, but there ia no updates for it
I have iOS 16.6.1

can you please check what is going on?

thank you

**Comment by enzofrnt** [comment]
Yes, the app as being update for IOS 17 so the 4.0 version..

**Comment by fmnamado** [comment]
I am sorry i don’t understand 
I have to update to iOS 17 in order to use the app?
Because it doesn’t appear to me as an option in the settings of the iPhone.

can you provide an option for iOS 16?

**Comment by rrroyal** [comment]
the full release of iOS 17 will be on 18th - sorry for complicating things, but please wait until then 😔

**Comment by fmnamado** [comment]
Ok no problem, I have to thank you because the app is amazing 
It is very convenient for me to restart containers and see logs

will be mandatory for me updating ios 17 to use your app?

are u planing to release the full app in the appstore?

thank you once again

**Comment by rrroyal** [comment]
yup, the v4 requires iOS 17
and yes, i'm planning to release the app on the App Store :)
