### ISSUE TITLE
Crashing on Launch

### ISSUE THREAD

**Issue by Wamy-Dev** [rrroyal/Harbour#21]
**Describe the bug**

**To Reproduce**
1. Install from IPA using Trollstore
2. (Try) to open app
**Expected behavior**
The app opens

**Details (please complete the following information):**
 - Device: [iPhone 12 Pro]
 - OS: [iOS 15.4]
 - Harbour version [v3.0.0#6]
 - Portainer version [NA]

**Additional context**
Opening does not open the app.

**Comment by rrroyal** [comment]
Harbour 3 only supports iOS 16, so it's not surprising that it crashes. You can try Harbour 2 :)
