### ISSUE TITLE
What is correct api url

### ISSUE THREAD

**Issue by malfunctioningEddy** [rrroyal/Harbour#22]
Hi,

With previous version Harbour was running perfectly.
Now with the new version I lost the endpoint config.
I can't seem to find the correct format.

My normal wb url is:
http://192.168.10.127:9000/#!/home

I tried adding the api with token as:
- http://192.168.10.127:9000
- http://192.168.10.127:9000/api

But to no avail.
I do see an added endpoint but can't select it in first screen.
![IMG_0476](https://user-images.githubusercontent.com/98105177/228853397-d06847fa-272b-4fe2-a3fb-eed5cc891080.PNG)
![IMG_0477](https://user-images.githubusercontent.com/98105177/228853509-a8e3e8ec-141d-478b-8399-f697f2f9db87.PNG)

**Comment by rrroyal** [comment]
I'm pretty sure you should use `http://192.168.10.127:9000` as the server URL. After that, refresh main screen (either scroll-to-refresh, or restart the app) and select an endpoint from the toolbar menu (tap on *No endpoint selected*).
If you still don't have any endpoints there, can you enter Settings → Debug → Logs and send me them to royal@shameful.xyz?
