### ISSUE TITLE
App Does Nothing After Setup

### ISSUE THREAD

**Issue by danperks** [rrroyal/Harbour#23]
**Describe the bug**
After setting up the app, I cannot pick an endpoint, even after refreshing the page and restarting the app.

The logs are empty and I get no error messages.

Any help would be great :)

**Screenshots**

![image](https://user-images.githubusercontent.com/49082234/235818774-3e6c15b7-264e-4977-aecf-92df01cbf3b8.png)
![image](https://user-images.githubusercontent.com/49082234/235818798-ece3ae40-4eb5-4b64-9176-f6e11d0ea97d.png)

**Comment by danperks** [comment]
If I try add the URL again, as a second URL, I get this error when switching between the two, but I can't see my expand it, and there's still no logs!

![image](https://user-images.githubusercontent.com/49082234/235818974-82f3e660-ac27-488e-b659-029b37618a4d.png)

**Comment by rrroyal** [comment]
you should be able to expand the notification by pulling on it.

what URL are you using to connect in Harbour?

**Comment by danperks** [comment]
URL is the same as my Portainer instance. Also, pulling on the error don't do anything, I did try when it happened!

![image](https://user-images.githubusercontent.com/49082234/235895550-61928c5a-4aba-4494-920e-1f87883d9f1f.png)

**Comment by danperks** [comment]
@sysadmininator Thanks for the suggestion. I had the pop up as soon as I opened the app for the first time, and the toggle is still enabled in the app settings. 

I'm at work right now but will experiment with some other ports later on.

**Comment by danperks** [comment]
> weird; you can try to:
> 
> 1. remove the server
> 
> 2. add it again
> 
> 3. refresh main screen
> 
> 4. open logs and wait for around 5-10s (until something shows up) - there should be something there 

Tried this, still no logs and no errors when there's only one server. Adding a second shows an error that I cannot expand.

**Comment by rrroyal** [comment]
are you using a self-signed SSL certificate by any chance?
