### ISSUE TITLE
App reset after closing

### ISSUE THREAD

**Issue by Jannomag** [rrroyal/Harbour#24]
**Describe the bug**
When closing the app from app switcher and restart the app all settings are gone and I need to relogin (which needs to create a new token each time)

**To Reproduce**
1. Start app and do the setup
2. Close the app from app switcher
3. Restart app

**Expected behavior**
Settings should be saved

**Details (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 16.4
 - Harbour version: 3.0.0
 - Portainer version: 2.18.3

**Container create command (if applicable)**:
`docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce`

**Additional context**
I sideloaded the app via Signulous. But I tried on TestFlight as well, same issue.

**Comment by rrroyal** [comment]
I'm not familiar with Signulous, but it could be fucking up the Keychain - if you have a macOS device, could You check if anything is being saved there?
1. Open `Keychain Access.app`
2. Search for `Harbour`. There should be some entries with the type `Harbour - Token`.

It's the first time I'm hearing about such issue, so it may be something wrong with your device. Are the UserDefaults settings being saved (*Use Grid View*, etc.)?

**Comment by rrroyal** [comment]
Yup, as far as I know it will happen in every case of sideloading - this isn't my priority, but I am investigating.

**Comment by jiznon** [comment]
Can confirm same issue here
