### ISSUE TITLE
Beta Expired

### ISSUE THREAD

**Issue by eximo84** [rrroyal/Harbour#25]
Beta expired message. App no longer showing in TestFlight for me. 

Link on the readme shows they TestFlight is full.

**Comment by ceviixx** [comment]
You can use the sourcecode - works also Great.
I ‚hosted’ it in my own TestFlight to install (no dev Mode on iPhone needed) 🥳

**Comment by eximo84** [comment]
> You can use the sourcecode - works also Great.
> I ‚hosted’ it in my own TestFlight to install (no dev Mode on iPhone needed) 🥳

Assume you need a mac though 🙁

**Comment by ceviixx** [comment]
> > You can use the sourcecode - works also Great.
> > I ‚hosted’ it in my own TestFlight to install (no dev Mode on iPhone needed) 🥳
> 
> Assume you need a mac though 🙁 

You‘re Right 👍🏼😖
Maybe @rrroyal will release a new Version?
Or release it in the App Store 😍

**Comment by rrroyal** [comment]
There is a iOS 17 version coming. In the meantime, I refreshed the existing build - 3.0.0 (11).
