### ISSUE TITLE
Add container health outout

### ISSUE THREAD

**Issue by mitchelv07** [rrroyal/Harbour#28]
Hi, 

First of all, awesome app! I really do enjoy it! It helps me alot managing my docker containers on the fly.

However, I am missing one small thing, and that is being able to check the container health and its output. For example, I have a container that continously pings and uses that for its health status. Is this possible to display in the app too?

Again, awesome job!

**Comment by rrroyal** [comment]
shipped in 4.1.1 - does it solve Your issue? 😃

**Comment by OctaVive** [comment]
Perfect! Works as expected, thanks!
