### ISSUE TITLE
V4 Testflight

### ISSUE THREAD

**Issue by Prolonz** [rrroyal/Harbour#29]
Not sure if this is just me but I’m still stuck on v3 in TestFlight and it expires in 3 days. 

Has v4 been pushed to TestFlight yet?

**Comment by rrroyal** [comment]
nope, v4 isn't public yet. should be out by the time iOS 17 releases (Sep 18)

**Comment by enzofrnt** [comment]
Hi, for people who are on RC we cannot get access ?

**Comment by rrroyal** [comment]
i'll release the build on TestFlight the moment App Review approves it :)
