### ISSUE TITLE
External stacks not visible

### ISSUE THREAD

**Issue by kiwiz** [rrroyal/Harbour#30]
**Describe the bug**
Portainer offers limited functionality for managing "external" stacks, which were spun up with `docker-compose`. I can see the individual containers in the main view, but the stacks view reports "No Containers". I can confirm that stacks set up from Portainer do show up in the UI

**To Reproduce**
1. Spin up a `docker-compose.yml` (outside of Portainer)
2. Check the Portainer UI - the stack should show up there
3. Check Harbour - the stack doesn't show up there

**Expected behavior**
Stacks created outside Portainer should be visible

**Details (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 17.0.1
 - Harbour version: 4.0.0
 - Portainer version: 2.19.1

**Comment by kiwiz** [comment]
On closer inspection, this is more of a feature request.

The `/stacks` endpoint returns only real stacks. The frontend actually hits `containers/json?all`, to enumerate all containers and appears to aggregate the results based on the `com.docker.compose.project` label. :thinking:

**Comment by rrroyal** [comment]
Fixed, will be released in 4.0.1 :)

**Comment by rrroyal** [comment]
released in 4.1.0!
