### ISSUE TITLE
Filter Stacks by Environment

### ISSUE THREAD

**Issue by Cossey** [rrroyal/Harbour#31]
The stacks button shows all stacks across all Environments on my Portainer. Could you please consider only showing stacks for the currently selected environment. 

I have three separate docker servers (not running in swarm mode) and some of them have the same stack names; when I select stacks in Harbour it shows the same stack three times, filtering this list will only show stacks of relevance for the environment I'm working in at the time. 

Thanks!

**Comment by rrroyal** [comment]
added in the upcoming release :)

**Comment by rrroyal** [comment]
released in 4.1.0!

**Comment by Cossey** [comment]
Was updating harbour on test flight to see these changes - still at 4.0.0; didn't realise this was fully released now! Might want to update the test flight version with a message saying that app is now out of beta and that you can buy on app store 🙂
