### ISSUE TITLE
view container IP address

### ISSUE THREAD

**Issue by drwb** [rrroyal/Harbour#36]
I run docker containers exclusively using macvlan networks and the ‘ports’ section is understandably empty. 

I’d like to see the ‘ports’ section as a ‘networks’ section and see the ip address(es) of the containers.

**Comment by pax0707** [comment]
Came here to suggest this exact thing.

**Comment by rrroyal** [comment]
updated in the next release :)

**Comment by rrroyal** [comment]
released in 4.1.1 - does it solve Your issue? 😀
