### ISSUE TITLE
Support for Instances behind reverse-proxy

### ISSUE THREAD

**Issue by MrDrache333** [rrroyal/Harbour#37]
**Is your feature request related to a problem? Please describe.**
For me it's not possible to connect to a portainer instance behind a reverse-proxy like Cloudflare. When I try to use my Domain like https://portainer.mydomain.de it will internally forward my request to the specific host and port like localhost:9001. This works well when you try to access the portainer instance on mobile devices or on a different network. 

**Describe the solution you'd like**
I would like to see a solution to connect to instances behind a reverse-proxy. Additionally a separated debug mode to see possible detailed error messages when connecting would be nice because I only see "Unknown Error".
Another great feature would be to make it possible to add custom headers to the connection. For example external used tokes to authenticate to Cloudflare access or other firewall solutions to bypass them.

**Additional Info**
I can provide you with a test-portainer instance with reverse proxy to test on if you like to.

**Comment by rrroyal** [comment]
If you're able to, please email me the address to the Portainer instance - I'll see what's going wrong!

As to the custom headers - implementing this would complicate a lot of things, and I prefer to keep the app as easy-to-use as possible. I know that it's not the same thing, but you can match requests based on UA (i.e. `Harbour/1 CFNetwork/1492.0.1 Darwin/23.3.0`) and `x-api-key` (the Portainer token) :)

**Comment by gentaz** [comment]
Just wanted to drop a note here to say that I have a similar issue on a different setup. I have my portainer at `https://portainer.my.domain` behind a Traefik reverse proxy on my server. Traefik handles the TLS connection and forwards requests to portainer's port 9000. I get the same `unknown error` on the app.

**Comment by kWeglinski** [comment]
Chiming in with a note - I'm running on reverse proxy without any issue. Main difference is it's selfhosted node proxy manager, running over vpn with custom DNS server. Worked out of the box. 
Standard settings for npm, portainer is running in http, npm slaps ssl on top.
