### ISSUE TITLE
Question about notifications 

### ISSUE THREAD

**Issue by davin900** [rrroyal/Harbour#39]
Hi,

I’m just trying to understand some of the notifications I receive from this app. I have successfully connected it to Portainer where I have about 20 running containers. 

But I only get the notification I’m referencing about Plex. 

Here’s what it says…

**D:I:Plexdows and D:R:Plexdows changed their states.**
D:I:Plexdows: Up 29 hours
D:R:Plexdows: Unknown

Plexdows is just what I called the container. 

But why are there two listed? I only have one container for Plex. And what does changed states mean? I check the logs for Plex and don’t see anything going on. And I don’t get these notifications for any other containers. 
Also what do D:I and D:R mean?

Im relatively new at Docker so apologies if I should know what these things mean. 

Thanks

**Comment by rrroyal** [comment]
oh shit i forgot i left them on, sorry about that

*... changed states* means that the container was last seen with a different state (running, stopped, paused, exited, etc.). this notification you're receiving is about a container being re-created (i.e. the image was updated, which means old container was removed, and a new one appeared).

`D:I` and `D:R` means *differences - inserted* and *differences - removed*, which are for notification debugging purposes. new build will have notifications working as they should :)
