### ISSUE TITLE
Stuck at loading

### ISSUE THREAD

**Issue by Martinvdm** [rrroyal/Harbour#4]
**Describe the bug**
Harbour is stuck at loading. When logging off and on again, all working fine. When the app is closed some time and want to reopen, it does not open. Stuck at loading , and on top “refreshing”

**Expected behavior**
A working refresh and login

**Details (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: ios 15.1
 - Harbour version 2.0.0(4)
 - Portainer version: 2.11.0

**Comment by Martinvdm** [comment]
![Uploading D4FCEA80-574D-4DA3-BBF6-4F15322F3666.jpeg…]()

**Comment by john5du** [comment]
Same issue.
![image](https://user-images.githubusercontent.com/45614150/151656631-e0f89a2d-9d6b-41c8-a80d-01828408c8ec.png)

**Comment by rrroyal** [comment]
(hopefully) fixed in next build!

**Comment by rrroyal** [comment]
please let me know if it works now (168a1e44618cd8bf1344b4413e2f36eea738c566 / v2.0.0#5) :)

**Comment by Martinvdm** [comment]
Great! Only i don’t know how to get your build in test flight :)

**Comment by rrroyal** [comment]
you can join [here](https://testflight.apple.com/join/F2vK7xo4) - it'll be live in a bit :)

**Comment by Martinvdm** [comment]
Seems to work . Thanks a lot
