### ISSUE TITLE
Docker swarm “container not found”

### ISSUE THREAD

**Issue by notnooblord** [rrroyal/Harbour#40]
**Describe the bug**
Basically when using harbour with docker swarm, i get overview of all containers present, but when clicking on one container seems to work 1 time out of 3 (maybe because i have 3 hosts)

**To Reproduce**
1. Go to your portainer endpoint
2. Click on any container
3. See error “container not found” (1 time out of host count?)

**Expected behavior**
See container description and buttons to view logs, etc.

**Details (please complete the following information):**
 - Device: iPhone Mini 13
 - OS: iOS 17.2.1
 - Harbour version [v4.0.0 (#34)](https://github.com/rrroyal/Harbour/releases/tag/v4.0.0-34)
 - Portainer version 2.19.4

**Screenshots:**

![IMG_4198](https://github.com/rrroyal/Harbour/assets/11678665/08571aaa-fb79-401e-92aa-2edb22a1b726)

**Comment by notnooblord** [comment]
Also all stacks show Active(0/0), maybe related to swarm.

**Comment by EFastner** [comment]
Any update on this issue? I am having the same behavior

**Comment by rrroyal** [comment]
I'm having troubles replicating the issue 😕
Could any of You either give me steps to replicate the environment, or give me access to the affected endpoint?

**Comment by rrroyal** [comment]
closed - if this keeps happening, please reopen!

**Comment by AtomicDude** [comment]
Hi, the error still appears. 

I’ve noticed that it happens when I’m trying to access services that aren’t deployed on the Portainer manager node.
