### ISSUE TITLE
Allow deployment of containers

### ISSUE THREAD

**Issue by wdreyer1318** [rrroyal/Harbour#43]
**Is your feature request related to a problem? Please describe.**
I cannot deploy any containers from the app period.

**Describe the solution you'd like**
A way to use the app templates feature of the portainer web ui to deploy containers.

**Describe alternatives you've considered**
Obvioudly the web ui works, but the point of the app is to not use the web ui

**Comment by rrroyal** [comment]
on the roadmap :)

**Comment by jclsn** [comment]
I was also hoping to be able to update stacks and get notified about new image versions

**Comment by rrroyal** [comment]
Updating stacks will be in the next release.
As to notifying about new versions - I recommend [watchtower](https://github.com/containrrr/watchtower) :)

**Comment by jclsn** [comment]
Thanks, I'll have a look :)

**Comment by rrroyal** [comment]
updating stacks has been released in 4.1.1, does it solve Your issue?

**Comment by jclsn** [comment]
I don't see where you can update stacks. You can only stop and start. Nowhere does it say that new images are downloaded and redeployed, although I have not checked if this is what actually happens under the hood.

**Comment by rrroyal** [comment]
open the context menu (by force touching the cell or tapping the three dots symbol in the toolbar of the stack details view) → "Edit"

**Comment by jclsn** [comment]
Works. Thx!
