### ISSUE TITLE
Unable to connect to server (404 error)

### ISSUE THREAD

**Issue by bohdan-s** [rrroyal/Harbour#44]
Good morning. 

I am having trouble connecting to my Portainer container. 
I have the correct URL and API key as I can make the API calls via curl and get a response. 

I am using Portainer BE 2.19 and App Store version of Harbour. 
I am connecting on port 9443 which is using a self signed certificate. 

All I get from the debug logs is:
Error: PortainerKit.Portainer.PortainerError.responseCodeUnacceptable(404)

**Comment by rrroyal** [comment]
Is your self-signed certificate trusted in iOS settings?

404 means that there's a problem with the URL, so maybe double check if the address is 100% correct?

**Comment by bohdan-s** [comment]
The url works via curl, I am using https://<ip>:9443
I can access the web ui of Portainer via safari and it works after clicking the “access this site anyway” button.

**Comment by rrroyal** [comment]
If there's a "Access this site anyway" prompt that means that the self-signed cert isn't trusted by iOS.

If you're able to, can you check which request is failing using some HTTP proxy?

**Comment by bohdan-s** [comment]
Ok. 
So I set up letsencrypt and a DNS record, generated a certificate and it connected. 

Can I request an additional feature to add a toggle to ignore self signed certificate errors?

**Comment by rrroyal** [comment]
yup, will try to accept self-signed certs by default
honestly i dont know either why it stopped working on v4 😶
