### ISSUE TITLE
I recently put Authentik in front of my Portainer URL for added security. But now Harbour cannot access. Is there a URL that I need to whitelist in Authentik?

### ISSUE THREAD

**Issue by davin900** [rrroyal/Harbour#45]
Title basically says it. I have an NGINX Proxy Manager URL that I use to access Portainer but began to realize how insecure that is so I put Authentik in front of it. 

But now I can’t use Harbour. I know there’s a feature in Authentik to not require authentication on a specific path for instances like this. Any idea what I should try?

thanks

**Comment by rrroyal** [comment]
I don't use Authentik, but I think you could try accepting requests if they come from Harbour (`User-Agent` header) + they have a valid authorization token (`X-API-Key=<value from Portainer>`).
