### ISSUE TITLE
SSL needed to connect to Portainer

### ISSUE THREAD

**Issue by Jenssaibe** [rrroyal/Harbour#46]
Bought this app, looks great but I can’t use it. 

**Is your feature request related to a problem? Please describe.**
Can’t connect to Portainer instance without SSL. I connect through local network (with or without VPN).  

**Describe the solution you'd like**
I would like to be able to connect to my portainer instance without HTTPS (or reverse proxy)

**Describe alternatives you've considered**
Refund, because I just can’t use it.

**Comment by Jenssaibe** [comment]
Sorry, my mistake. Thought I couldn’t access Portainer with https but I can.

**Comment by rrroyal** [comment]
Welp, glad you got it figured out!
