### ISSUE TITLE
iPadOS Widgets don't open container

### ISSUE THREAD

**Issue by Runesmite** [rrroyal/Harbour#48]
**Describe the bug**
On my iPhone, it works as expected. If I tap a container in a widget, it opens in the harbour app. If I tap a container in a widget on iPad OS, it shows a yellow caution sign.

This happens on all widgets (1, 2, and 4 containers)

**To Reproduce**
1. Add widget to iPad home screen.
2. Add containers to widget.
3. Tap container in widget.

**Expected behavior**
It's expected to operate as it does on IOS where the specific container that was tapped opens up in harbour

**Details (please complete the following information):**
 - Device: iPad Pro 11" (3rd Generation)
 - OS: iPadOS 17.4.1
 - Harbour version: v4.1.0
 - Portainer version: 2.19.4

**Container create command (if applicable)**:
n/a

**Additional context**
none

**Screenshots**
none

**Comment by rrroyal** [comment]
This is a bug that is tied to `NavigationSplitView`. Fixing it would require a lot of refactoring, so hopefully it will be fixed in iOS 18 🤞

**Comment by Runesmite** [comment]
Good to know! I will keep an eye out. Hopefully it is fixed. Thank you.
