### ISSUE TITLE
Control Center integration for iOS/iPadOS 18+

### ISSUE THREAD

**Issue by codefruitio** [rrroyal/Harbour#49]
Apple announced today at WWDC24 the ability for developers to make buttons for their apps in Control Center. It would be awesome to use this API to control the state of select containers, similar to toggling a HomeKit accessory

https://developer.apple.com/documentation/swiftui/controlwidget

**Comment by rrroyal** [comment]
yup, will be exploring that in 5.0 :)

**Comment by rrroyal** [comment]
the newest release (4.2.0) has improved Intents support - you can create a shortcut and add it in the Control Center :)
