### ISSUE TITLE
Widgets for container status

### ISSUE THREAD

**Issue by Nahydrin** [rrroyal/Harbour#5]
**Is your feature request related to a problem? Please describe.**
Not related to any problem.

**Describe the solution you'd like**
Widgets that show container status (online, stopped, crashed, whatever portainer knows)

**Unrelated**
Not sure if it's on the feature list, but ram/cpu usage per container as well

**Comment by rrroyal** [comment]
coming in next build :)

**Comment by rrroyal** [comment]
live from 168a1e44618cd8bf1344b4413e2f36eea738c566 :) please let me know how they work for you!
