### ISSUE TITLE
User agent

### ISSUE THREAD

**Issue by LucifersCircle** [rrroyal/Harbour#52]
**Is your feature request related to a problem? Please describe.**

Accessing the server with local ip is fine for when I'm home, but I'd kind of like to allow Harbour to bypass certain rules in my waf on cloudflare. Currently the user agent seems to be reported as `Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1 `

(I'm not sure if this is accurate, it's difficult to pinpoint the right log)

**Describe the solution you'd like**

I was wondering if you could add something to the user agent/change it, so that it could be used to identify Harbour.

**Comment by LucifersCircle** [comment]
Sorry, after a lot more digging I did find that there is a Harbour user agent and I was mistaken earlier!

`Harbour/46 CFNetwork/ Darwin/`

**Comment by rrroyal** [comment]
Hey, just to add to it - please make sure that UA isn't the only thing you're checking, as it could be easily manipulated. I personally use [Tailscale](https://tailscale.com)'s addresses so that I don't have to accept any incoming connections from the general web.
