### ISSUE TITLE
MacOS app Opacity effect visibility issue

### ISSUE THREAD

**Issue by codefruitio** [rrroyal/Harbour#55]
**Describe the bug**
On the macOS app (4.2.0 #50), the reduced opacity effect on the app window looks really nice, but it it might be a little too strong. If the app is on top of a lighter wallpaper/window, it makes it hard or sometimes impossible to see the outline of the various container grid items. In my screenshot below, you can see as the wallpaper gets darker lower on the screen, the visibility improves dramatically.

![CleanShot 2024-09-30 at 11 42 42@2x](https://github.com/user-attachments/assets/6bd4fb5e-7b64-4427-80d0-858e332b5e1d)

**Comment by rrroyal** [comment]
oh yeah that ain't good 😕 i'll fix it in the next release!

**Comment by rrroyal** [comment]
fixed in 4.2.1!
