### ISSUE TITLE
Does not work on iPad 

### ISSUE THREAD

**Issue by DBa20-24** [rrroyal/Harbour#56]
**Describe the bug**
After connecting to a portainer, I only get a "no selected endpoint" screen (see attachment). Tapping on it does not bring up any selection, nor does any kind of refresh (pull down and refresh, force-close app...)

**To Reproduce**
1. connect to portainer
2. Look at the screen
![IMG_0564](https://github.com/user-attachments/assets/2bab0c64-4ced-42d9-a16f-6472969a89a5)

**Expected behavior**
I expect to see containers managed by this portainer instance. Same config on my iPhone works.

**Details (please complete the following information):**
 - Device: iPad Pro 11"
 - OS: iPadOS 18.0.1
 - Harbour version 4.2.0#50
 - Portainer version 2.21.3

**Container create command (if applicable)**:
Unknown, too long ago

**Additional context**
Same config works on my iPhone 16 pro, with iOS 18.0.1

**Screenshots**

**Comment by rrroyal** [comment]
it should work if you have only one endpoint (as then it would automatically select it). otherwise, you need to select one yourself, but it's kinda hard to do that if there's no endpoint picker in the toolbar :/
i'll fix it in the next release!

**Comment by DBa20-24** [comment]
Interesting enough, there is a picker in the iPhone version, but not on the iPad.

**Comment by GEngines** [comment]
I managed to repro this issue, and it's a UI bug causing the options to be not visible, split the screen with 2 apps and shrink the Harbour screen space into 1/3 and the dropdown option returns

**Comment by rrroyal** [comment]
> I have 2 endpoints and I managed to repro this issue, and it's a UI bug causing the options to be not visible on iPad, split the screen with 2 apps and shrink the Harbour screen space into 1/3 which mimics iPhone screen size and the dropdown option returns 
> 
> ![image](https://github.com/user-attachments/assets/ca7e12fc-8f5c-4e59-8889-376a62f58c96)
> 
> I didn't want to leave a bug as review on App Store so had to hunt for this git thread, glad it's here!
> 
> @rrroyal 

oh yeah that also works! thanks for sharing and not leaving a bad review :) will fix it this week!

**Comment by rrroyal** [comment]
fixed in 4.2.1!
