### ISSUE TITLE
Expire TestFlight IOS

### ISSUE THREAD

**Issue by thisiscrazy2701** [rrroyal/Harbour#6]
Hi,

Hopefully you are already aware but the TestFlight version is going to expire in 9 days. 

Is there maybe a new version with lots of goodies?

Many thanks

**Comment by rrroyal** [comment]
Hiya!
I am aware of this - I'm cooking up some good stuff in the next build (currently trying to debug widgets, hopefully they will be ready before expiry date 😶‍🌫️)
