### ISSUE TITLE
Enable IOS 17 Support

### ISSUE THREAD

**Issue by NadirBourazza** [rrroyal/Harbour#60]
Hey there,

I used to be a user of the Apple TestFlight version of the app, and planned to purchase the app.

I was about to buy the app today however I noticed iOS 18 is now the only supported version. I recall the app used to work on iOS 17.

Would it be possible to re-add support for those who have not upgraded yet.

Thanks!

**Comment by rrroyal** [comment]
heyo! unfortunately, it's not just flipping a switch - there's stuff that was introduced only in iOS 18 😕 i'll see what i can do, but i can't promise anything

**Comment by NadirBourazza** [comment]
Thanks for getting back to me,

That makes sense, I wasn’t too sure how recent the features were that you are using (Swift is not my forte).

Either way, I’m sure I’ll upgrade to iOS 18 some time in the near term anyway. 

Thanks!
