### ISSUE TITLE
Starting containers fails with error: "starting container with non empty request body was deprecated..."

### ISSUE THREAD

**Issue by mac-tron** [rrroyal/Harbour#61]
**Describe the bug**
When starting a container, it fails with the error message:
> starting container with non empty request body was deprecated since AP...  (cutoff)

**To Reproduce**
1. Select container
2. Click on ... top right
3. Select start

**Expected behavior**
Container should start.

**Details (please complete the following information):**
 - Device: iPhone 13
 - OS: 18.0.1
 - Harbour version v4.2.1
 - Portainer Business Edition v2.22.4

**Additional context**

**Screenshots**
![image](https://github.com/user-attachments/assets/94b44e63-0de8-419d-a69b-a41e1f6061f0)

**Comment by rrroyal** [comment]
not good, will fix asap!

**Comment by LORDWORLD10** [comment]
Ďakujem pekne za ochotu 🙂

Dňa ut, 29. okt 2024, 7:44 rrroyal ***@***.***> napísal(a):

**Comment by rrroyal** [comment]
I'm unable to replicate your issue, but I think I fixed it - could you give me your email, so that I can invite you to TestFlight and you can see for yourself?

**Comment by mac-tron** [comment]
Thank you! I’ve downloaded the TestFlight and confirmed this has fixed the issue. 🙏

**Comment by rrroyal** [comment]
fixed in [v4.2.2-54](https://github.com/rrroyal/Harbour/releases/tag/v4.2.2-54)
