### ISSUE TITLE
Support showing images cpu ram.

### ISSUE THREAD

**Issue by DecoAri** [rrroyal/Harbour#62]
Hello developer.

I wish Harbour can showing the images. Also can manage images.

And. Wish each containers can showing their cpu ram usages.

Thanks

**Comment by DecoAri** [comment]
Also. If you use TestFlight frequently. Can I join? lol

**Comment by DecoAri** [comment]
Another things.

If I add a compose manually. Something error. I cannot read all error messages. Also cannot found in logs. So should harbour record error messages?

**Comment by rrroyal** [comment]
> I wish Harbour can showing the images. Also can manage images.

On the roadmap!

> And. Wish each containers can showing their cpu ram usages.

Not really planning on implementing that - if Portainer doesn't support it, Harbour will most likely also not support it.

> Also. If you use TestFlight frequently. Can I join? lol

TestFlight isn't used anymore (except for shipping hotfixes or major releases).

> If I add a compose manually. Something error. I cannot read all error messages. Also cannot found in logs. So should harbour record error messages?

If something errors out, you can expand the error indicator (by dragging it down) or check the logs (*Settings → Debug → Logs*). Without additional information, there's not much I can do.
