### ISSUE TITLE
Unable to login in the App to Portainer

### ISSUE THREAD

**Issue by SemoTech** [rrroyal/Harbour#8]
**Describe the bug**
Unable to login into the app. 

**To Reproduce**

On LAN, after installing from TestFlight and trying to authenticate I provide Portainer URL (https://192.168.0.100:9000) the portainer admin username and password and all I get is a spinning loader. No error no login. 

Access to Portainer using same credentials and url works fine from a lan browser. 
**Expected behavior**
Able to login!

**Details (please complete the following information):**
 - Device: iPhone 12Pro Max
 - OS: iOS 15.1.1
 - Harbour version: latest from TestFlight
 - Portainer version: latesr

**Container create command (if applicable)**:
*e.g. `docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce`*

**Additional context**

**Screenshots**

**Comment by rrroyal** [comment]
are you running the default configuration? if so, the correct port is `9443`, not `9000`

**Comment by SemoTech** [comment]
#
![67BA9C48-9901-4C5C-9D52-8D49D3DF8B71](https://user-images.githubusercontent.com/1452100/160631242-2b565614-dc6a-44e2-8ac3-68572d1864ba.jpeg)
![5A360E28-B67B-4C5B-A1FD-C7D946D5CAF8](https://user-images.githubusercontent.com/1452100/160631249-eed4a70e-f8d1-4f67-928c-872fae9f7cf4.jpeg)

**Comment by rrroyal** [comment]
try to expand the error indicator by dragging it down - it should tell us more

**Comment by SemoTech** [comment]
![1F82814E-19A4-41E7-A330-EA1C7BF4F51D](https://user-images.githubusercontent.com/1452100/160635844-5fdf4ba5-d861-4d2c-bb9d-0457c766f702.jpeg)

**Comment by rrroyal** [comment]
when you click the tag, select any endpoint (anything above "Refresh") - it will be autoselected in the coming build

**Comment by SemoTech** [comment]
YES! Finally worked and loaded all the Docker containers. Thank you.
