### ISSUE TITLE
Error "Invalid URL" with correct Portainer URL

### ISSUE THREAD

**Issue by Tech-Non** [rrroyal/Harbour#9]
**Describe the bug**
I am entering my Portainer endpoint which is located at https://my.domain.com/portainer/ (trailing slash is important here) and add my credentials to login. I get the error message "Invalid URL" even though the endpoint works and I can login at that URL in the browser.

**To Reproduce**
Login with an external HTTPS Portainer URL and subpath e.g. /portainer/ that ends in a trailing slash

**Expected behavior**
I should be able to login with my external URL

**Details (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 15.3.1
 - Harbour version v2.0.0#5
 - Portainer version 2.11.1

**Additional context**
If I enter the address without "https://" I get an endlessly spinning circle.
If I enter my internal Container IP address and Port http://xxx.xxx.xxx.xxx:9000 I can login.

The Container is deployed normally with a docker compose file and exposed via Traefik. Though my current setup explicitly needs the URL to end in /portainer/ with the trailing slash.

**Comment by waschinski** [comment]
I got this too using a subdomain with https, but no subfolder. Looks like everything is working fine even though I get error messages on basically every action I do (API calls I assume).

**Comment by Wamy-Dev** [comment]
happens to me as well. just went with ip:port instead.

**Comment by rrroyal** [comment]
Is this still happening?

**Comment by Tech-Non** [comment]
I don't use this configuration anymore, I have switched to a subdomain, but I tried it on a friends server just now who uses portainer with /portainer suffix in the url and it worked there!
